/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stats/grumbles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 投稿統計取得
         * @description 日/週/月ごとの成仏済み・未成仏・いいね数を返す
         */
        get: operations["getGrumbleStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/grumbles/toxic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 投稿統計取得（毒度別）
         * @description 日/週/月ごとの毒度別成仏・未成仏・いいね数を返す
         */
        get: operations["getGrumbleStatsToxic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grumbles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * タイムライン取得
         * @description 愚痴投稿を新しい順に取得
         */
        get: operations["getGrumbles"];
        put?: never;
        /**
         * 投稿作成
         * @description 新しい愚痴を投稿
         */
        post: operations["createGrumble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grumbles/{grumble_id}/vibes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 「わかる…」を送る
         * @description 指定された投稿に「わかる…」を押す
         */
        post: operations["addVibe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 自分のユーザー情報取得
         * @description ログインユーザーの情報を取得
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * イベント一覧取得
         * @description 現在開催中のイベント一覧を取得
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * イベント詳細取得
         * @description 指定されたイベントの詳細情報を取得
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/grumbles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * イベント投稿取得
         * @description 24:00〜12:00の時間帯にアーカイブされた前日の投稿を取得
         */
        get: operations["getEventGrumbles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Grumble: {
            /**
             * Format: uuid
             * @description 投稿の一意識別子
             */
            grumble_id: string;
            /**
             * Format: uuid
             * @description 投稿者の匿名ID
             */
            user_id: string;
            /** @description 愚痴の本文 */
            content: string;
            /** @description 毒レベル（1〜5） */
            toxic_level: number;
            /** @description 「わかる…」の総数 */
            vibe_count: number;
            /**
             * @description 「わかる…」の数に応じたランク
             * @enum {string}
             */
            vibe_rank?: "見習い行者" | "弥勒" | "地蔵" | "大菩薩";
            /** @description 成仏するまでに必要な「わかる…」の数 */
            purified_threshold: number;
            /** @description 成仏フラグ */
            is_purified: boolean;
            /**
             * Format: date-time
             * @description 投稿時刻
             */
            posted_at: string;
            /**
             * Format: date-time
             * @description 投稿後24時間後の時刻
             */
            expires_at: string;
            /** @description イベント投稿か否か */
            is_event_grumble: boolean;
            /** @description ログインユーザーが「わかる…」済みか */
            has_vibed?: boolean;
        };
        CreateGrumbleRequest: {
            /** @description 愚痴の本文 */
            content: string;
            /** @description 毒レベル（1〜5） */
            toxic_level: number;
            /** @description 成仏するまでに必要な「わかる…」の数（オプション、未指定の場合はデフォルト値） */
            purified_threshold?: number;
            /**
             * @description イベント投稿か否か
             * @default false
             */
            is_event_grumble: boolean;
        };
        Vibe: {
            /** @description 共感履歴の一意識別子 */
            vibe_id: number;
            /**
             * Format: uuid
             * @description 共感対象の投稿ID
             */
            grumble_id: string;
            /**
             * Format: uuid
             * @description 共感した匿名ユーザーID
             */
            user_id: string;
            /**
             * @description 共感の種類
             * @enum {string}
             */
            vibe_type: "WAKARU";
            /**
             * Format: date-time
             * @description 共感した時刻
             */
            voted_at: string;
        };
        AnonymousUser: {
            /**
             * Format: uuid
             * @description 匿名ユーザーの一意識別子
             */
            user_id: string;
            /** @description 徳ポイント */
            virtue_points: number;
            /**
             * @description わかる数（徳ポイント）に応じたランク
             * @enum {string}
             */
            virtue_rank?: "見習い行者" | "弥勒" | "地蔵" | "大菩薩";
            /**
             * Format: date-time
             * @description ユーザー作成日時
             */
            created_at: string;
            /** @description 称号（例：「今週の菩薩」） */
            profile_title?: string | null;
        };
        Event: {
            /** @description イベントの一意識別子 */
            event_id: number;
            /** @description イベントの名称 */
            event_name: string;
            /**
             * @description イベントの種類
             * @enum {string}
             */
            event_type: "DAIONRYO" | "OTAKINAGE";
            /**
             * Format: date-time
             * @description イベント開始時刻
             */
            start_time: string;
            /**
             * Format: date-time
             * @description イベント終了時刻
             */
            end_time: string;
            /** @description 大怨霊の現在HP */
            current_hp?: number | null;
            /** @description 大怨霊の最大HP */
            max_hp?: number | null;
            /** @description 現在開催中のイベントか否か */
            is_active: boolean;
        };
        TimelineFilter: {
            /** @description 毒レベルの最小値 */
            toxic_level_min?: number;
            /** @description 毒レベルの最大値 */
            toxic_level_max?: number;
            /** @description 成仏済みかどうかで絞り込み（未指定の場合はすべて） */
            is_purified?: boolean;
            /**
             * @description 取得件数
             * @default 20
             */
            limit: number;
            /**
             * @description オフセット
             * @default 0
             */
            offset: number;
        };
        GrumbleStatsBucket: {
            /**
             * Format: date-time
             * @description 集計バケット開始時刻（UTC）
             */
            bucket: string;
            /** @description 成仏済み件数 */
            purified_count: number;
            /** @description 未成仏件数 */
            unpurified_count: number;
            /** @description いいね（vibe_count）の合計 */
            total_vibes: number;
        };
        GrumbleStatsToxicBucket: {
            /**
             * Format: date-time
             * @description 集計バケット開始時刻（UTC）
             */
            bucket: string;
            /** @description 毒度レベル */
            toxic_level: number;
            /** @description 成仏済み件数 */
            purified_count: number;
            /** @description 未成仏件数 */
            unpurified_count: number;
            /** @description いいね（vibe_count）の合計 */
            total_vibes: number;
        };
        ErrorResponse: {
            /**
             * @description エラーコード
             * @example DUPLICATE_VIBE
             */
            error: string;
            /**
             * @description エラーメッセージ
             * @example 既にこの投稿に「わかる…」を送信しています
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGrumbleStats: {
        parameters: {
            query: {
                /**
                 * @description 集計粒度
                 * @example day
                 */
                granularity: "day" | "week" | "month";
                /**
                 * @description 期間開始（省略時はバックエンドがデフォルト期間を設定）
                 * @example 2025-11-01T00:00:00Z
                 */
                from?: string;
                /**
                 * @description 期間終了（非含む。省略時はデフォルト期間を設定）
                 * @example 2025-11-08T00:00:00Z
                 */
                to?: string;
                /**
                 * @description タイムゾーン（例: Asia/Tokyo）。未指定はサーバ既定
                 * @example Asia/Tokyo
                 */
                tz?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 統計結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrumbleStatsBucket"][];
                };
            };
            /** @description 不正なリクエスト */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGrumbleStatsToxic: {
        parameters: {
            query: {
                /**
                 * @description 集計粒度
                 * @example week
                 */
                granularity: "day" | "week" | "month";
                /**
                 * @description 期間開始（省略時はバックエンドがデフォルト期間を設定）
                 * @example 2025-10-01T00:00:00Z
                 */
                from?: string;
                /**
                 * @description 期間終了（非含む。省略時はデフォルト期間を設定）
                 * @example 2025-11-01T00:00:00Z
                 */
                to?: string;
                /**
                 * @description タイムゾーン（例: Asia/Tokyo）。未指定はサーバ既定
                 * @example Asia/Tokyo
                 */
                tz?: string;
                /**
                 * @description 毒度レベルを指定するとそのレベルのみを返す
                 * @example 3
                 */
                toxic_level?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 毒度別統計結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrumbleStatsToxicBucket"][];
                };
            };
            /** @description 不正なリクエスト */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getGrumbles: {
        parameters: {
            query?: {
                /** @description 取得対象のユーザーID */
                user_id?: string;
                toxic_level_min?: number;
                toxic_level_max?: number;
                /** @description 成仏済みかどうかで絞り込み */
                is_purified?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投稿リスト */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        grumbles?: components["schemas"]["Grumble"][];
                        /** @description 総件数 */
                        total?: number;
                    };
                };
            };
            /** @description リクエストエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createGrumble: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrumbleRequest"];
            };
        };
        responses: {
            /** @description 投稿成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grumble"];
                };
            };
            /** @description リクエストエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addVibe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grumble_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @default WAKARU
                     * @enum {string}
                     */
                    vibe_type?: "WAKARU";
                };
            };
        };
        responses: {
            /** @description 共感成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vibe"];
                };
            };
            /** @description リクエストエラー（バリデーションエラーなど） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 投稿が見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 既にvibeを送信済み（競合） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymousUser"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description イベント一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events?: components["schemas"]["Event"][];
                    };
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description イベント詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description イベントが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEventGrumbles: {
        parameters: {
            query?: {
                /** @description 毒レベルの最小値 */
                toxic_level_min?: number;
                /** @description 毒レベルの最大値 */
                toxic_level_max?: number;
                /** @description 取得件数 */
                limit?: number;
                /** @description オフセット */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description イベント投稿リスト */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description イベント投稿リスト */
                        grumbles: components["schemas"]["Grumble"][];
                        /** @description 総件数 */
                        total: number;
                        /** @description イベント期間中（24:00〜12:00）かどうか */
                        is_event_active: boolean;
                        /**
                         * Format: date
                         * @description イベント対象日（YYYY-MM-DD）
                         */
                        event_date: string;
                    };
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
