/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/grumbles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * タイムライン取得
         * @description 愚痴投稿を新しい順に取得
         */
        get: operations["getGrumbles"];
        put?: never;
        /**
         * 投稿作成
         * @description 新しい愚痴を投稿
         */
        post: operations["createGrumble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grumbles/{grumble_id}/vibes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 「わかる…」を送る
         * @description 指定された投稿に「わかる…」を押す
         */
        post: operations["addVibe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 自分のユーザー情報取得
         * @description ログインユーザーの情報を取得
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * イベント一覧取得
         * @description 現在開催中のイベント一覧を取得
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * イベント詳細取得
         * @description 指定されたイベントの詳細情報を取得
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Grumble: {
            /**
             * Format: uuid
             * @description 投稿の一意識別子
             */
            grumble_id: string;
            /**
             * Format: uuid
             * @description 投稿者の匿名ID
             */
            user_id: string;
            /** @description 愚痴の本文 */
            content: string;
            /** @description 毒レベル（1〜5） */
            toxic_level: number;
            /** @description 「わかる…」の総数 */
            vibe_count: number;
            /** @description 成仏フラグ */
            is_purified: boolean;
            /**
             * Format: date-time
             * @description 投稿時刻
             */
            posted_at: string;
            /**
             * Format: date-time
             * @description 投稿後24時間後の時刻
             */
            expires_at: string;
            /** @description イベント投稿か否か */
            is_event_grumble: boolean;
            /** @description ログインユーザーが「わかる…」済みか */
            has_vibed?: boolean;
        };
        CreateGrumbleRequest: {
            /** @description 愚痴の本文 */
            content: string;
            /** @description 毒レベル（1〜5） */
            toxic_level: number;
            /**
             * @description イベント投稿か否か
             * @default false
             */
            is_event_grumble: boolean;
        };
        Vibe: {
            /** @description 共感履歴の一意識別子 */
            vibe_id: number;
            /**
             * Format: uuid
             * @description 共感対象の投稿ID
             */
            grumble_id: string;
            /**
             * Format: uuid
             * @description 共感した匿名ユーザーID
             */
            user_id: string;
            /**
             * @description 共感の種類
             * @enum {string}
             */
            vibe_type: "WAKARU";
            /**
             * Format: date-time
             * @description 共感した時刻
             */
            voted_at: string;
        };
        AnonymousUser: {
            /**
             * Format: uuid
             * @description 匿名ユーザーの一意識別子
             */
            user_id: string;
            /** @description 徳ポイント */
            virtue_points: number;
            /**
             * Format: date-time
             * @description ユーザー作成日時
             */
            created_at: string;
            /** @description 称号（例：「今週の菩薩」） */
            profile_title?: string | null;
        };
        Event: {
            /** @description イベントの一意識別子 */
            event_id: number;
            /** @description イベントの名称 */
            event_name: string;
            /**
             * @description イベントの種類
             * @enum {string}
             */
            event_type: "DAIONRYO" | "OTAKINAGE";
            /**
             * Format: date-time
             * @description イベント開始時刻
             */
            start_time: string;
            /**
             * Format: date-time
             * @description イベント終了時刻
             */
            end_time: string;
            /** @description 大怨霊の現在HP */
            current_hp?: number | null;
            /** @description 大怨霊の最大HP */
            max_hp?: number | null;
            /** @description 現在開催中のイベントか否か */
            is_active: boolean;
        };
        TimelineFilter: {
            /** @description 毒レベルの最小値 */
            toxic_level_min?: number;
            /** @description 毒レベルの最大値 */
            toxic_level_max?: number;
            /**
             * @description 未成仏のみ表示
             * @default false
             */
            unpurified_only: boolean;
            /**
             * @description 取得件数
             * @default 20
             */
            limit: number;
            /**
             * @description オフセット
             * @default 0
             */
            offset: number;
        };
        ErrorResponse: {
            /** @description エラーコード */
            error: string;
            /** @description エラーメッセージ */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGrumbles: {
        parameters: {
            query?: {
                toxic_level_min?: number;
                toxic_level_max?: number;
                unpurified_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 投稿リスト */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        grumbles?: components["schemas"]["Grumble"][];
                        /** @description 総件数 */
                        total?: number;
                    };
                };
            };
            /** @description リクエストエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createGrumble: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrumbleRequest"];
            };
        };
        responses: {
            /** @description 投稿成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grumble"];
                };
            };
            /** @description リクエストエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addVibe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grumble_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @default WAKARU
                     * @enum {string}
                     */
                    vibe_type?: "WAKARU";
                };
            };
        };
        responses: {
            /** @description 共感成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vibe"];
                };
            };
            /** @description リクエストエラー（既に押済みなど） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 投稿が見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymousUser"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description イベント一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events?: components["schemas"]["Event"][];
                    };
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description イベント詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description イベントが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
